// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AudioResponse.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AudioResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace omnimusic {

namespace {

const ::google::protobuf::Descriptor* AudioResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AudioResponse_2eproto() {
  protobuf_AddDesc_AudioResponse_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AudioResponse.proto");
  GOOGLE_CHECK(file != NULL);
  AudioResponse_descriptor_ = file->message_type(0);
  static const int AudioResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioResponse, written_),
  };
  AudioResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioResponse_descriptor_,
      AudioResponse::default_instance_,
      AudioResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AudioResponse_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioResponse_descriptor_, &AudioResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AudioResponse_2eproto() {
  delete AudioResponse::default_instance_;
  delete AudioResponse_reflection_;
}

void protobuf_AddDesc_AudioResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023AudioResponse.proto\022\tomnimusic\" \n\rAudi"
    "oResponse\022\017\n\007written\030\001 \002(\005", 66);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AudioResponse.proto", &protobuf_RegisterTypes);
  AudioResponse::default_instance_ = new AudioResponse();
  AudioResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AudioResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AudioResponse_2eproto {
  StaticDescriptorInitializer_AudioResponse_2eproto() {
    protobuf_AddDesc_AudioResponse_2eproto();
  }
} static_descriptor_initializer_AudioResponse_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AudioResponse::kWrittenFieldNumber;
#endif  // !_MSC_VER

AudioResponse::AudioResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AudioResponse::InitAsDefaultInstance() {
}

AudioResponse::AudioResponse(const AudioResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AudioResponse::SharedCtor() {
  _cached_size_ = 0;
  written_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AudioResponse::~AudioResponse() {
  SharedDtor();
}

void AudioResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AudioResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioResponse_descriptor_;
}

const AudioResponse& AudioResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AudioResponse_2eproto();
  return *default_instance_;
}

AudioResponse* AudioResponse::default_instance_ = NULL;

AudioResponse* AudioResponse::New() const {
  return new AudioResponse;
}

void AudioResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    written_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 written = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &written_)));
          set_has_written();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AudioResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 written = 1;
  if (has_written()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->written(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AudioResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 written = 1;
  if (has_written()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->written(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AudioResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 written = 1;
    if (has_written()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->written());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioResponse::MergeFrom(const AudioResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_written()) {
      set_written(from.written());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioResponse::CopyFrom(const AudioResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void AudioResponse::Swap(AudioResponse* other) {
  if (other != this) {
    std::swap(written_, other->written_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioResponse_descriptor_;
  metadata.reflection = AudioResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace omnimusic

// @@protoc_insertion_point(global_scope)
