// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AudioData.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AudioData.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace omnimusic {

namespace {

const ::google::protobuf::Descriptor* AudioData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AudioData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AudioData_2eproto() {
  protobuf_AddDesc_AudioData_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AudioData.proto");
  GOOGLE_CHECK(file != NULL);
  AudioData_descriptor_ = file->message_type(0);
  static const int AudioData_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, samples_),
  };
  AudioData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AudioData_descriptor_,
      AudioData::default_instance_,
      AudioData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AudioData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AudioData));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AudioData_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AudioData_descriptor_, &AudioData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AudioData_2eproto() {
  delete AudioData::default_instance_;
  delete AudioData_reflection_;
}

void protobuf_AddDesc_AudioData_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017AudioData.proto\022\tomnimusic\"\034\n\tAudioDat"
    "a\022\017\n\007samples\030\001 \002(\014", 58);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AudioData.proto", &protobuf_RegisterTypes);
  AudioData::default_instance_ = new AudioData();
  AudioData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AudioData_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AudioData_2eproto {
  StaticDescriptorInitializer_AudioData_2eproto() {
    protobuf_AddDesc_AudioData_2eproto();
  }
} static_descriptor_initializer_AudioData_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AudioData::kSamplesFieldNumber;
#endif  // !_MSC_VER

AudioData::AudioData()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AudioData::InitAsDefaultInstance() {
}

AudioData::AudioData(const AudioData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AudioData::SharedCtor() {
  _cached_size_ = 0;
  samples_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AudioData::~AudioData() {
  SharedDtor();
}

void AudioData::SharedDtor() {
  if (samples_ != &::google::protobuf::internal::kEmptyString) {
    delete samples_;
  }
  if (this != default_instance_) {
  }
}

void AudioData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AudioData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AudioData_descriptor_;
}

const AudioData& AudioData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AudioData_2eproto();
  return *default_instance_;
}

AudioData* AudioData::default_instance_ = NULL;

AudioData* AudioData::New() const {
  return new AudioData;
}

void AudioData::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_samples()) {
      if (samples_ != &::google::protobuf::internal::kEmptyString) {
        samples_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AudioData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes samples = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_samples()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AudioData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes samples = 1;
  if (has_samples()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->samples(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* AudioData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes samples = 1;
  if (has_samples()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->samples(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int AudioData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes samples = 1;
    if (has_samples()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->samples());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AudioData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AudioData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AudioData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AudioData::MergeFrom(const AudioData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_samples()) {
      set_samples(from.samples());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AudioData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AudioData::CopyFrom(const AudioData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AudioData::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void AudioData::Swap(AudioData* other) {
  if (other != this) {
    std::swap(samples_, other->samples_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AudioData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AudioData_descriptor_;
  metadata.reflection = AudioData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace omnimusic

// @@protoc_insertion_point(global_scope)
