// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BufferInfo.proto

#ifndef PROTOBUF_BufferInfo_2eproto__INCLUDED
#define PROTOBUF_BufferInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace omnimusic {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BufferInfo_2eproto();
void protobuf_AssignDesc_BufferInfo_2eproto();
void protobuf_ShutdownFile_BufferInfo_2eproto();

class BufferInfo;

// ===================================================================

class BufferInfo : public ::google::protobuf::Message {
 public:
  BufferInfo();
  virtual ~BufferInfo();

  BufferInfo(const BufferInfo& from);

  inline BufferInfo& operator=(const BufferInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BufferInfo& default_instance();

  void Swap(BufferInfo* other);

  // implements Message ----------------------------------------------

  BufferInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BufferInfo& from);
  void MergeFrom(const BufferInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 samples = 1;
  inline bool has_samples() const;
  inline void clear_samples();
  static const int kSamplesFieldNumber = 1;
  inline ::google::protobuf::int32 samples() const;
  inline void set_samples(::google::protobuf::int32 value);

  // required int32 stutter = 2;
  inline bool has_stutter() const;
  inline void clear_stutter();
  static const int kStutterFieldNumber = 2;
  inline ::google::protobuf::int32 stutter() const;
  inline void set_stutter(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:omnimusic.BufferInfo)
 private:
  inline void set_has_samples();
  inline void clear_has_samples();
  inline void set_has_stutter();
  inline void clear_has_stutter();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 samples_;
  ::google::protobuf::int32 stutter_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_BufferInfo_2eproto();
  friend void protobuf_AssignDesc_BufferInfo_2eproto();
  friend void protobuf_ShutdownFile_BufferInfo_2eproto();

  void InitAsDefaultInstance();
  static BufferInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// BufferInfo

// required int32 samples = 1;
inline bool BufferInfo::has_samples() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BufferInfo::set_has_samples() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BufferInfo::clear_has_samples() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BufferInfo::clear_samples() {
  samples_ = 0;
  clear_has_samples();
}
inline ::google::protobuf::int32 BufferInfo::samples() const {
  return samples_;
}
inline void BufferInfo::set_samples(::google::protobuf::int32 value) {
  set_has_samples();
  samples_ = value;
}

// required int32 stutter = 2;
inline bool BufferInfo::has_stutter() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BufferInfo::set_has_stutter() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BufferInfo::clear_has_stutter() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BufferInfo::clear_stutter() {
  stutter_ = 0;
  clear_has_stutter();
}
inline ::google::protobuf::int32 BufferInfo::stutter() const {
  return stutter_;
}
inline void BufferInfo::set_stutter(::google::protobuf::int32 value) {
  set_has_stutter();
  stutter_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace omnimusic

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BufferInfo_2eproto__INCLUDED
