// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FormatInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FormatInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace omnimusic {

namespace {

const ::google::protobuf::Descriptor* FormatInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FormatInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FormatInfo_2eproto() {
  protobuf_AddDesc_FormatInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FormatInfo.proto");
  GOOGLE_CHECK(file != NULL);
  FormatInfo_descriptor_ = file->message_type(0);
  static const int FormatInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormatInfo, sampling_rate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormatInfo, channels_),
  };
  FormatInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FormatInfo_descriptor_,
      FormatInfo::default_instance_,
      FormatInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormatInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FormatInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FormatInfo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FormatInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FormatInfo_descriptor_, &FormatInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FormatInfo_2eproto() {
  delete FormatInfo::default_instance_;
  delete FormatInfo_reflection_;
}

void protobuf_AddDesc_FormatInfo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020FormatInfo.proto\022\tomnimusic\"5\n\nFormatI"
    "nfo\022\025\n\rsampling_rate\030\001 \002(\005\022\020\n\010channels\030\002"
    " \002(\005", 84);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FormatInfo.proto", &protobuf_RegisterTypes);
  FormatInfo::default_instance_ = new FormatInfo();
  FormatInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FormatInfo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FormatInfo_2eproto {
  StaticDescriptorInitializer_FormatInfo_2eproto() {
    protobuf_AddDesc_FormatInfo_2eproto();
  }
} static_descriptor_initializer_FormatInfo_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int FormatInfo::kSamplingRateFieldNumber;
const int FormatInfo::kChannelsFieldNumber;
#endif  // !_MSC_VER

FormatInfo::FormatInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FormatInfo::InitAsDefaultInstance() {
}

FormatInfo::FormatInfo(const FormatInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FormatInfo::SharedCtor() {
  _cached_size_ = 0;
  sampling_rate_ = 0;
  channels_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FormatInfo::~FormatInfo() {
  SharedDtor();
}

void FormatInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FormatInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FormatInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FormatInfo_descriptor_;
}

const FormatInfo& FormatInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FormatInfo_2eproto();
  return *default_instance_;
}

FormatInfo* FormatInfo::default_instance_ = NULL;

FormatInfo* FormatInfo::New() const {
  return new FormatInfo;
}

void FormatInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    sampling_rate_ = 0;
    channels_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FormatInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 sampling_rate = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sampling_rate_)));
          set_has_sampling_rate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_channels;
        break;
      }

      // required int32 channels = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_channels:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channels_)));
          set_has_channels();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FormatInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 sampling_rate = 1;
  if (has_sampling_rate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->sampling_rate(), output);
  }

  // required int32 channels = 2;
  if (has_channels()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->channels(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FormatInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 sampling_rate = 1;
  if (has_sampling_rate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->sampling_rate(), target);
  }

  // required int32 channels = 2;
  if (has_channels()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->channels(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FormatInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 sampling_rate = 1;
    if (has_sampling_rate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->sampling_rate());
    }

    // required int32 channels = 2;
    if (has_channels()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->channels());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FormatInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FormatInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FormatInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FormatInfo::MergeFrom(const FormatInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_sampling_rate()) {
      set_sampling_rate(from.sampling_rate());
    }
    if (from.has_channels()) {
      set_channels(from.channels());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FormatInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FormatInfo::CopyFrom(const FormatInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FormatInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void FormatInfo::Swap(FormatInfo* other) {
  if (other != this) {
    std::swap(sampling_rate_, other->sampling_rate_);
    std::swap(channels_, other->channels_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FormatInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FormatInfo_descriptor_;
  metadata.reflection = FormatInfo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace omnimusic

// @@protoc_insertion_point(global_scope)
